
-- 1. Create mandaps table
CREATE TABLE IF NOT EXISTS public.mandaps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    area TEXT,
    address TEXT,
    google_maps_url TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    contact_email TEXT,
    contact_phone TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add missing columns if the table already exists
ALTER TABLE public.mandaps ADD COLUMN IF NOT EXISTS area TEXT;
ALTER TABLE public.mandaps ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE public.mandaps ADD COLUMN IF NOT EXISTS google_maps_url TEXT;
ALTER TABLE public.mandaps ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE public.mandaps ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;
ALTER TABLE public.mandaps ADD COLUMN IF NOT EXISTS contact_email TEXT;
ALTER TABLE public.mandaps ADD COLUMN IF NOT EXISTS contact_phone TEXT;
ALTER TABLE public.mandaps ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE public.mandaps ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 2. Photos table
ALTER TABLE public.photos ADD COLUMN IF NOT EXISTS uploader_email TEXT;
ALTER TABLE public.photos ADD COLUMN IF NOT EXISTS uploader_phone TEXT;
ALTER TABLE public.photos ALTER COLUMN uploader_email DROP NOT NULL;

-- 3. Enable RLS
ALTER TABLE public.mandaps ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anyone can submit mandap request"
ON public.mandaps;

CREATE POLICY "anyone can submit mandap request"
ON public.mandaps
FOR INSERT
TO anon, authenticated
WITH CHECK (status = 'pending');

-- 4. Check policies
SELECT tablename, policyname, cmd, roles
FROM pg_policies
WHERE schemaname = 'public'
AND tablename IN ('mandaps', 'photos')
ORDER BY tablename, policyname;

