
-- Allow email or phone contact for photo uploads
ALTER TABLE public.photos
ADD COLUMN IF NOT EXISTS uploader_phone TEXT;

-- Make email optional (if it is currently NOT NULL)
ALTER TABLE public.photos
ALTER COLUMN uploader_email DROP NOT NULL;


CREATE TABLE IF NOT EXISTS public.mandap_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mandap_name TEXT NOT NULL,
  area TEXT,
  address TEXT,
  google_maps_url TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  contact_email TEXT,
  contact_phone TEXT,
  submission_type TEXT NOT NULL
    CHECK (submission_type IN ('existing_map', 'new_mandap')),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT mandap_contact_required CHECK (
    NULLIF(TRIM(contact_email), '') IS NOT NULL
    OR NULLIF(TRIM(contact_phone), '') IS NOT NULL
  )
);

ALTER TABLE public.mandap_requests
ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can submit mandap requests"
ON public.mandap_requests
FOR INSERT
TO anon, authenticated
WITH CHECK (status = 'pending');